// Code generated by protoc-gen-go.
// source: common.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type ErrorResponse struct {
	Error *Error `protobuf:"bytes,9,opt,name=error" json:"error,omitempty"`
}

func (m *ErrorResponse) Reset()                    { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string            { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()               {}
func (*ErrorResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ErrorResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	Code      string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Detail    string `protobuf:"bytes,3,opt,name=detail" json:"detail,omitempty"`
	Temporary bool   `protobuf:"varint,4,opt,name=temporary" json:"temporary,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *Error) GetTemporary() bool {
	if m != nil {
		return m.Temporary
	}
	return false
}

func init() {
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*ErrorResponse)(nil), "pb.ErrorResponse")
	proto.RegisterType((*Error)(nil), "pb.Error")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x44, 0xce, 0x3b, 0x0e, 0xc2, 0x30,
	0x0c, 0x80, 0x61, 0xa5, 0xf4, 0x41, 0x0c, 0x2c, 0x1e, 0x50, 0x06, 0x24, 0xaa, 0x4e, 0x9d, 0x2a,
	0x04, 0x67, 0xe8, 0x05, 0x7a, 0x83, 0x3e, 0x2c, 0x84, 0x20, 0x75, 0xe4, 0x64, 0xe9, 0xed, 0x11,
	0x29, 0x88, 0xcd, 0xff, 0x67, 0x0f, 0x86, 0xfd, 0xc8, 0xd6, 0xf2, 0xdc, 0x38, 0xe1, 0xc0, 0x98,
	0xb8, 0xa1, 0x2a, 0x20, 0x6b, 0xad, 0x0b, 0x4b, 0x75, 0x81, 0x43, 0x2b, 0xc2, 0xd2, 0x91, 0x77,
	0x3c, 0x7b, 0xc2, 0x33, 0x64, 0xf4, 0x01, 0xa3, 0x4b, 0x55, 0xef, 0xae, 0xba, 0x71, 0x43, 0xb3,
	0x5e, 0xac, 0x5e, 0x3d, 0x21, 0x8b, 0x8d, 0x08, 0xe9, 0xc8, 0x13, 0x19, 0x55, 0xaa, 0x5a, 0x77,
	0x71, 0x46, 0x03, 0x85, 0x25, 0xef, 0xfb, 0x3b, 0x99, 0x24, 0xf2, 0x2f, 0xf1, 0x08, 0xf9, 0x44,
	0xa1, 0x7f, 0xbc, 0xcc, 0x26, 0x2e, 0xbe, 0x85, 0x27, 0xd0, 0x81, 0xac, 0x63, 0xe9, 0x65, 0x31,
	0x69, 0xa9, 0xea, 0x6d, 0xf7, 0x87, 0x21, 0x8f, 0x2f, 0xdf, 0xde, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x82, 0xee, 0x9d, 0xa6, 0xc2, 0x00, 0x00, 0x00,
}
